-- CreateTable
CREATE TABLE "Match" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "dataVersion" TEXT NOT NULL,
    "gameCreation" BIGINT NOT NULL,
    "gameDuration" BIGINT NOT NULL,
    "gameEndTimestamp" BIGINT NOT NULL,
    "gameId" BIGINT NOT NULL,
    "gameMode" TEXT NOT NULL,
    "gameName" TEXT NOT NULL,
    "gameStartTimestamp" BIGINT NOT NULL,
    "gameType" TEXT NOT NULL,
    "gameVersion" TEXT NOT NULL,
    "mapId" INTEGER NOT NULL,
    "platformId" TEXT NOT NULL,
    "queueId" INTEGER NOT NULL,
    "tournamentCode" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "SummonerMatchParticipation" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "matchId" TEXT NOT NULL,
    "summonerId" TEXT NOT NULL,
    "participantId" TEXT NOT NULL,
    CONSTRAINT "SummonerMatchParticipation_matchId_fkey" FOREIGN KEY ("matchId") REFERENCES "Match" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "SummonerMatchParticipation_summonerId_fkey" FOREIGN KEY ("summonerId") REFERENCES "Summoner" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "SummonerMatchParticipation_participantId_fkey" FOREIGN KEY ("participantId") REFERENCES "Participant" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Participant" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "matchId" TEXT NOT NULL,
    "assists" INTEGER NOT NULL,
    "baronKills" INTEGER NOT NULL,
    "basicPings" INTEGER NOT NULL,
    "bountyLevel" INTEGER NOT NULL,
    "champExperience" INTEGER NOT NULL,
    "champLevel" INTEGER NOT NULL,
    "championId" INTEGER NOT NULL,
    "championName" TEXT NOT NULL,
    "championTransform" INTEGER NOT NULL,
    "consumablesPurchased" INTEGER NOT NULL,
    "damageDealtToBuildings" INTEGER NOT NULL,
    "damageDealtToObjectives" INTEGER NOT NULL,
    "damageDealtToTurrets" INTEGER NOT NULL,
    "damageSelfMitigated" INTEGER NOT NULL,
    "deaths" INTEGER NOT NULL,
    "detectorWardsPlaced" INTEGER NOT NULL,
    "doubleKills" INTEGER NOT NULL,
    "dragonKills" INTEGER NOT NULL,
    "eligibleForProgression" BOOLEAN NOT NULL,
    "firstBloodAssist" BOOLEAN NOT NULL,
    "firstBloodKill" BOOLEAN NOT NULL,
    "firstTowerAssist" BOOLEAN NOT NULL,
    "firstTowerKill" BOOLEAN NOT NULL,
    "gameEndedInEarlySurrender" BOOLEAN NOT NULL,
    "gameEndedInSurrender" BOOLEAN NOT NULL,
    "goldEarned" INTEGER NOT NULL,
    "goldSpent" INTEGER NOT NULL,
    "individualPosition" TEXT NOT NULL,
    "inhibitorKills" INTEGER NOT NULL,
    "inhibitorTakedowns" INTEGER NOT NULL,
    "inhibitorsLost" INTEGER NOT NULL,
    "item0" INTEGER NOT NULL,
    "item1" INTEGER NOT NULL,
    "item2" INTEGER NOT NULL,
    "item3" INTEGER NOT NULL,
    "item4" INTEGER NOT NULL,
    "item5" INTEGER NOT NULL,
    "item6" INTEGER NOT NULL,
    "itemsPurchased" INTEGER NOT NULL,
    "killingSprees" INTEGER NOT NULL,
    "kills" INTEGER NOT NULL,
    "lane" TEXT NOT NULL,
    "largestCriticalStrike" INTEGER NOT NULL,
    "largestKillingSpree" INTEGER NOT NULL,
    "largestMultiKill" INTEGER NOT NULL,
    "longestTimeSpentLiving" INTEGER NOT NULL,
    "magicDamageDealt" INTEGER NOT NULL,
    "magicDamageDealtToChampions" INTEGER NOT NULL,
    "magicDamageTaken" INTEGER NOT NULL,
    "neutralMinionsKilled" INTEGER NOT NULL,
    "nexusKills" INTEGER NOT NULL,
    "nexusLost" INTEGER NOT NULL,
    "nexusTakedowns" INTEGER NOT NULL,
    "objectivesStolen" INTEGER NOT NULL,
    "objectivesStolenAssists" INTEGER NOT NULL,
    "pentaKills" INTEGER NOT NULL,
    "physicalDamageDealt" INTEGER NOT NULL,
    "physicalDamageDealtToChampions" INTEGER NOT NULL,
    "physicalDamageTaken" INTEGER NOT NULL,
    "profileIcon" INTEGER NOT NULL,
    "puuid" TEXT NOT NULL,
    "quadraKills" INTEGER NOT NULL,
    "riotIdName" TEXT NOT NULL,
    "riotIdTagline" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "sightWardsBoughtInGame" INTEGER NOT NULL,
    "spell1Casts" INTEGER NOT NULL,
    "spell2Casts" INTEGER NOT NULL,
    "spell3Casts" INTEGER NOT NULL,
    "spell4Casts" INTEGER NOT NULL,
    "summoner1Casts" INTEGER NOT NULL,
    "summoner1Id" INTEGER NOT NULL,
    "summoner2Casts" INTEGER NOT NULL,
    "summoner2Id" INTEGER NOT NULL,
    "summonerId" TEXT NOT NULL,
    "summonerLevel" INTEGER NOT NULL,
    "summonerName" TEXT NOT NULL,
    "teamEarlySurrendered" BOOLEAN NOT NULL,
    "teamId" INTEGER NOT NULL,
    "teamPosition" TEXT NOT NULL,
    "timeCCingOthers" INTEGER NOT NULL,
    "timePlayed" BIGINT NOT NULL,
    "totalDamageDealt" INTEGER NOT NULL,
    "totalDamageDealtToChampions" INTEGER NOT NULL,
    "totalDamageShieldedOnTeammates" INTEGER NOT NULL,
    "totalDamageTaken" INTEGER NOT NULL,
    "totalHeal" INTEGER NOT NULL,
    "totalHealsOnTeammates" INTEGER NOT NULL,
    "totalMinionsKilled" INTEGER NOT NULL,
    "totalTimeCCDealt" INTEGER NOT NULL,
    "totalTimeSpentDead" INTEGER NOT NULL,
    "totalUnitsHealed" INTEGER NOT NULL,
    "tripleKills" INTEGER NOT NULL,
    "trueDamageDealt" INTEGER NOT NULL,
    "trueDamageDealtToChampions" INTEGER NOT NULL,
    "trueDamageTaken" INTEGER NOT NULL,
    "turretKills" INTEGER NOT NULL,
    "turretTakedowns" INTEGER NOT NULL,
    "turretsLost" INTEGER NOT NULL,
    "unrealKills" INTEGER NOT NULL,
    "visionScore" INTEGER NOT NULL,
    "visionWardsBoughtInGame" INTEGER NOT NULL,
    "wardsKilled" INTEGER NOT NULL,
    "wardsPlaced" INTEGER NOT NULL,
    "win" BOOLEAN NOT NULL,
    CONSTRAINT "Participant_matchId_fkey" FOREIGN KEY ("matchId") REFERENCES "Match" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "SummonerMatchParticipation_summonerId_matchId_key" ON "SummonerMatchParticipation"("summonerId", "matchId");

-- CreateIndex
CREATE UNIQUE INDEX "SummonerMatchParticipation_participantId_matchId_key" ON "SummonerMatchParticipation"("participantId", "matchId");
